package metadata

import (
	"bytes"
	"encoding/binary"
	"hash/crc32"
	"testing"
)

func TestStripProvenance_PNG_RemovesTextAndCustomChunks(t *testing.T) {
	var buf bytes.Buffer
	buf.Write([]byte{137, 80, 78, 71, 13, 10, 26, 10})
	writeChunk(&buf, "IHDR", []byte{0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0})
	writeChunk(&buf, "iTXt", []byte("XML:com.adobe.xmp\x00\x00\x00\x00\x00<x:xmpmeta>...</x:xmpmeta>"))
	writeChunk(&buf, "tEXt", []byte("Comment\x00generated by gpt-image-2"))
	writeChunk(&buf, "eXIf", []byte{0x49, 0x49, 0x2A, 0x00})
	writeChunk(&buf, "caBX", []byte("c2pa-manifest-bytes-go-here"))
	writeChunk(&buf, "IDAT", []byte{0x78, 0xDA, 0x62, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF})
	writeChunk(&buf, "IEND", nil)

	out, err := StripProvenance(buf.Bytes())
	if err != nil {
		t.Fatalf("StripProvenance: %v", err)
	}

	if !bytes.Equal(out[:8], []byte{137, 80, 78, 71, 13, 10, 26, 10}) {
		t.Fatal("output missing PNG signature")
	}
	for _, drop := range []string{"iTXt", "tEXt", "eXIf", "caBX"} {
		if bytes.Contains(out, []byte(drop)) {
			t.Errorf("expected %s chunk to be stripped", drop)
		}
	}
	for _, keep := range []string{"IHDR", "IDAT", "IEND"} {
		if !bytes.Contains(out, []byte(keep)) {
			t.Errorf("expected %s chunk to be preserved", keep)
		}
	}
}

func TestStripProvenance_PNG_PreservesBitIdenticalMinimal(t *testing.T) {
	var buf bytes.Buffer
	buf.Write([]byte{137, 80, 78, 71, 13, 10, 26, 10})
	writeChunk(&buf, "IHDR", []byte{0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0})
	writeChunk(&buf, "IDAT", []byte{0x78, 0xDA, 0x62, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF})
	writeChunk(&buf, "IEND", nil)

	in := buf.Bytes()
	out, err := StripProvenance(in)
	if err != nil {
		t.Fatalf("StripProvenance: %v", err)
	}
	if !bytes.Equal(in, out) {
		t.Fatal("minimal PNG should be byte-identical after strip")
	}
}

func TestStripProvenance_JPEG_DropsAPPnAndCOM(t *testing.T) {
	var buf bytes.Buffer
	buf.Write([]byte{0xFF, 0xD8}) // SOI
	writeJPEGSegment(&buf, 0xE0, []byte("JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"))
	writeJPEGSegment(&buf, 0xE1, []byte("Exif\x00\x00II*\x00..."))
	writeJPEGSegment(&buf, 0xEB, []byte("JP\x00\x0bc2pa-manifest-jumbf-data"))
	writeJPEGSegment(&buf, 0xFE, []byte("Comment text"))
	writeJPEGSegment(&buf, 0xDB, []byte{0x00, 0x01, 0x02, 0x03})
	writeJPEGSegment(&buf, 0xDA, []byte{0x01, 0x01, 0x00, 0x00, 0x3F, 0x00})
	buf.Write([]byte{0x12, 0x34, 0xFF, 0x00, 0x56, 0x78}) // entropy data with stuffed 0xFF
	buf.Write([]byte{0xFF, 0xD9})                         // EOI

	out, err := StripProvenance(buf.Bytes())
	if err != nil {
		t.Fatalf("StripProvenance: %v", err)
	}

	if !bytes.HasPrefix(out, []byte{0xFF, 0xD8}) {
		t.Fatal("output missing SOI")
	}
	if !bytes.HasSuffix(out, []byte{0xFF, 0xD9}) {
		t.Fatal("output missing EOI")
	}
	for _, drop := range [][]byte{[]byte("JFIF"), []byte("Exif"), []byte("c2pa-manifest"), []byte("Comment text")} {
		if bytes.Contains(out, drop) {
			t.Errorf("expected %q to be stripped", drop)
		}
	}
	// DQT (0xDB) and SOS (0xDA) markers + entropy should survive.
	if !bytes.Contains(out, []byte{0xFF, 0xDB}) {
		t.Error("expected DQT segment to survive")
	}
	if !bytes.Contains(out, []byte{0xFF, 0xDA}) {
		t.Error("expected SOS segment to survive")
	}
	if !bytes.Contains(out, []byte{0xFF, 0x00}) {
		t.Error("expected stuffed 0xFF in entropy stream to survive")
	}
}

func TestStripProvenance_WebP_DropsMetaChunksAndClearsFlags(t *testing.T) {
	body := bytes.NewBuffer(nil)
	// VP8X with EXIF + XMP flags set, plus extra dims.
	vp8x := []byte{0x0C, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	writeRIFFChunk(body, "VP8X", vp8x)
	writeRIFFChunk(body, "VP8 ", []byte{0x00, 0x01, 0x02, 0x03})
	writeRIFFChunk(body, "EXIF", []byte("II*\x00...exif..."))
	writeRIFFChunk(body, "XMP ", []byte("<x:xmpmeta>...</x:xmpmeta>"))
	writeRIFFChunk(body, "C2PA", []byte("c2pa-manifest-bytes"))

	var file bytes.Buffer
	file.WriteString("RIFF")
	_ = binary.Write(&file, binary.LittleEndian, uint32(4+body.Len()))
	file.WriteString("WEBP")
	file.Write(body.Bytes())

	out, err := StripProvenance(file.Bytes())
	if err != nil {
		t.Fatalf("StripProvenance: %v", err)
	}

	if !bytes.HasPrefix(out, []byte("RIFF")) || !bytes.Equal(out[8:12], []byte("WEBP")) {
		t.Fatal("output missing RIFF/WEBP container")
	}
	for _, drop := range []string{"EXIF", "XMP ", "C2PA"} {
		if bytes.Contains(out[12:], []byte(drop)) {
			t.Errorf("expected %q chunk to be stripped", drop)
		}
	}
	for _, keep := range []string{"VP8X", "VP8 "} {
		if !bytes.Contains(out[12:], []byte(keep)) {
			t.Errorf("expected %q chunk to be preserved", keep)
		}
	}
	// VP8X flag byte (first data byte of the chunk) must have EXIF/XMP bits cleared.
	idx := bytes.Index(out, []byte("VP8X"))
	if idx < 0 {
		t.Fatal("VP8X chunk missing")
	}
	flags := out[idx+8]
	if flags&0x0C != 0 {
		t.Errorf("expected EXIF/XMP flags cleared in VP8X, got 0x%02x", flags)
	}

	// RIFF size header must equal the new body size.
	wantSize := uint32(len(out) - 8)
	gotSize := binary.LittleEndian.Uint32(out[4:8])
	if gotSize != wantSize {
		t.Errorf("RIFF size header = %d, want %d", gotSize, wantSize)
	}
}

func TestStripProvenance_UnknownFormatPassthrough(t *testing.T) {
	in := []byte("not an image, just bytes")
	out, err := StripProvenance(in)
	if err != nil {
		t.Fatalf("StripProvenance: %v", err)
	}
	if !bytes.Equal(in, out) {
		t.Fatal("expected unknown format to be returned unchanged")
	}
}

func writeChunk(buf *bytes.Buffer, chunkType string, data []byte) {
	_ = binary.Write(buf, binary.BigEndian, uint32(len(data)))
	buf.WriteString(chunkType)
	buf.Write(data)
	crc := crc32.ChecksumIEEE(append([]byte(chunkType), data...))
	_ = binary.Write(buf, binary.BigEndian, crc)
}

func writeJPEGSegment(buf *bytes.Buffer, marker byte, payload []byte) {
	buf.WriteByte(0xFF)
	buf.WriteByte(marker)
	_ = binary.Write(buf, binary.BigEndian, uint16(len(payload)+2))
	buf.Write(payload)
}

func writeRIFFChunk(buf *bytes.Buffer, fourcc string, data []byte) {
	buf.WriteString(fourcc)
	_ = binary.Write(buf, binary.LittleEndian, uint32(len(data)))
	buf.Write(data)
	if len(data)%2 == 1 {
		buf.WriteByte(0)
	}
}
